# Generated by Django 5.1.5 on 2025-03-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
                "db_table": "admission",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="building/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "db_table": "building",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Chair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="chair/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chair",
                "verbose_name_plural": "Chairs",
                "db_table": "chair",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Cooperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="cooperation/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cooperation",
                "verbose_name_plural": "Cooperations",
                "db_table": "cooperation",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="document/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "document",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="info/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
                "db_table": "info",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="interview/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "verbose_name_plural": "Interviews",
                "db_table": "interview",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="laboratory/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
                "db_table": "laboratory",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Sub Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Contact"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="leadership/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership",
                "verbose_name_plural": "Leaderships",
                "db_table": "leadership",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
                "db_table": "news_category",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="rating/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "db_table": "rating",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="news/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "student",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BuildingGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        db_index=True,
                        upload_to="building/gallery/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="backend.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building Gallery",
                "verbose_name_plural": "Building Galleries",
                "db_table": "building_gallery",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ChairContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Value"
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("TELEGRAM", "Telegram"),
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("TWITTER", "Twitter"),
                            ("LINKEDIN", "LinkedIn"),
                            ("WEBSITE", "Website"),
                            ("YOUTUBE", "YouTube"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=255,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="backend.chair",
                        verbose_name="Chair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chair Contact",
                "verbose_name_plural": "Chair Contacts",
                "db_table": "chair_contact",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ChairMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="chair/member/", verbose_name="Image"
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="backend.chair",
                        verbose_name="Chair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chair Member",
                "verbose_name_plural": "Chair Members",
                "db_table": "chair_member",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LaboratoryGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        db_index=True,
                        upload_to="laboratory/gallery/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_galleries",
                        to="backend.laboratory",
                        verbose_name="Laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory Gallery",
                "verbose_name_plural": "Laboratory Galleries",
                "db_table": "laboratory_gallery",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        db_index=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="news/", verbose_name="Image"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.newscategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "news",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                ("content", models.TextField(db_index=True, verbose_name="Content")),
                (
                    "image",
                    models.ImageField(
                        db_index=True, upload_to="testimonial/", verbose_name="Image"
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="backend.chair",
                        verbose_name="Chair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "db_table": "testimonial",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        db_index=True,
                        max_length=255,
                        verbose_name="Day",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(db_index=True, verbose_name="Start Time"),
                ),
                ("end_time", models.TimeField(db_index=True, verbose_name="End Time")),
                (
                    "leadership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_timelines",
                        to="backend.leadership",
                        verbose_name="Leadership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Timeline",
                "verbose_name_plural": "Work Timelines",
                "db_table": "work_timeline",
                "ordering": ("-created_at",),
            },
        ),
    ]
