# Generated by Django 5.1.5 on 2025-03-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Value"
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("TELEGRAM", "Telegram"),
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("TWITTER", "Twitter"),
                            ("LINKEDIN", "LinkedIn"),
                            ("WEBSITE", "Website"),
                            ("YOUTUBE", "YouTube"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=255,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="backend.info",
                        verbose_name="Info",
                    ),
                ),
            ],
            options={
                "verbose_name": "Info Contact",
                "verbose_name_plural": "Info Contacts",
                "db_table": "info_contact",
                "ordering": ("-created_at",),
            },
        ),
    ]
