# Generated by Django 5.1.5 on 2025-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_infocontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chairmember",
            options={
                "ordering": ["position"],
                "verbose_name": "Chair Member",
                "verbose_name_plural": "Chair Members",
            },
        ),
        migrations.AlterModelOptions(
            name="leadership",
            options={
                "ordering": ("position",),
                "verbose_name": "Leadership",
                "verbose_name_plural": "Leaderships",
            },
        ),
        migrations.AddField(
            model_name="chairmember",
            name="position",
            field=models.BigIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AddField(
            model_name="leadership",
            name="position",
            field=models.BigIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
    ]
