# Generated by Django 5.1.5 on 2025-02-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_newscategory_news_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadership",
            name="name",
        ),
        migrations.RemoveField(
            model_name="leadership",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="leadership",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="leadership",
            name="name_uz",
        ),
    ]
