# Generated by Django 5.1.5 on 2025-02-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_remove_leadership_name_remove_leadership_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadership",
            name="contact",
            field=models.CharField(default=1, max_length=255, verbose_name="Contact"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leadership",
            name="sub_title",
            field=models.CharField(default=1, max_length=255, verbose_name="Sub Title"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "image",
                    models.ImageField(upload_to="testimonial/", verbose_name="Image"),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="backend.chair",
                        verbose_name="Chair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=255,
                        verbose_name="Day",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "leadership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_timelines",
                        to="backend.leadership",
                        verbose_name="Leadership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
