# Generated by Django 5.1.5 on 2025-03-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_admission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="backend.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building Gallery",
                "verbose_name_plural": "Building Galleries",
            },
        ),
    ]
