# Generated by Django 5.1.5 on 2025-03-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_chaircontact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admission",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.AlterModelOptions(
            name="buildinggallery",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Building Gallery",
                "verbose_name_plural": "Building Galleries",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="worktimeline",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Work Timeline",
                "verbose_name_plural": "Work Timelines",
            },
        ),
        migrations.AlterModelTable(
            name="admission",
            table="admission",
        ),
        migrations.AlterModelTable(
            name="building",
            table="building",
        ),
        migrations.AlterModelTable(
            name="buildinggallery",
            table="building_gallery",
        ),
        migrations.AlterModelTable(
            name="chair",
            table="chair",
        ),
        migrations.AlterModelTable(
            name="chaircontact",
            table="chair_contact",
        ),
        migrations.AlterModelTable(
            name="chairmember",
            table="chair_member",
        ),
        migrations.AlterModelTable(
            name="cooperation",
            table="cooperation",
        ),
        migrations.AlterModelTable(
            name="document",
            table="document",
        ),
        migrations.AlterModelTable(
            name="info",
            table="info",
        ),
        migrations.AlterModelTable(
            name="interview",
            table="interview",
        ),
        migrations.AlterModelTable(
            name="laboratory",
            table="laboratory",
        ),
        migrations.AlterModelTable(
            name="laboratorygallery",
            table="laboratory_gallery",
        ),
        migrations.AlterModelTable(
            name="leadership",
            table="leadership",
        ),
        migrations.AlterModelTable(
            name="news",
            table="news",
        ),
        migrations.AlterModelTable(
            name="newscategory",
            table="news_category",
        ),
        migrations.AlterModelTable(
            name="rating",
            table="rating",
        ),
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
        migrations.AlterModelTable(
            name="testimonial",
            table="testimonial",
        ),
        migrations.AlterModelTable(
            name="worktimeline",
            table="work_timeline",
        ),
    ]
