# Generated by Django 5.1.5 on 2025-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_alter_admission_options_alter_building_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="admission",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="image",
            field=models.ImageField(db_index=True, upload_to="", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="admission",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="admission",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="description",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="description_en",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="description_ru",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="description_uz",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="building/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="building",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="buildinggallery",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="building/gallery/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="chair",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="chair/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="chair",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="chair",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chair",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chaircontact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("PHONE", "Phone"),
                    ("TELEGRAM", "Telegram"),
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("TWITTER", "Twitter"),
                    ("LINKEDIN", "LinkedIn"),
                    ("WEBSITE", "Website"),
                    ("YOUTUBE", "YouTube"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=255,
                verbose_name="Contact Type",
            ),
        ),
        migrations.AlterField(
            model_name="chaircontact",
            name="value",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="chair/member/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="chairmember",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="cooperation/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="cooperation",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description_en",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description_ru",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description_uz",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="document/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="info",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="info/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="info",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="info",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="interview",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="interview/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="interview",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="laboratory/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="laboratorygallery",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="laboratory/gallery/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="contact",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Contact"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="leadership/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="sub_title",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Sub Title"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="leadership",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="news/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="description",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="description_en",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="description_ru",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="description_uz",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="rating/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="description",
            field=models.TextField(db_index=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="student",
            name="description_en",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="description_ru",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="description_uz",
            field=models.TextField(
                db_index=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="news/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="title",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="student",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(db_index=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                db_index=True, upload_to="testimonial/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="worktimeline",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                db_index=True,
                max_length=255,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="worktimeline",
            name="end_time",
            field=models.TimeField(db_index=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="worktimeline",
            name="start_time",
            field=models.TimeField(db_index=True, verbose_name="Start Time"),
        ),
    ]
